### PR TITLE
Fixed last name with 2 compound prefixes

### PR DESCRIPTION
**Pull request by gkoychev**

### CODE REVIEW

**Comment by gkoychev** [comment]
could you please publish it to npm?

**Comment by mklaber** [comment]
@gkoychev  I was going to but it looked like NPM picked up the new version (v.0.0.3): https://www.npmjs.com/package/another-name-parser

**Comment by mklaber** [comment]
I take that back. Picked up the version but not the update. Hold plz.

**Comment by mklaber** [comment]
All set.

**Comment by gkoychev** [comment]
thanks)

**Comment by jcruiz** [comment]
great thanks @mklaber for merging and @gkoychev for the fix. We are a fan of the module!

**Pull request merged**
